### ISSUE TITLE
question about scenario

### ISSUE THREAD

**Issue by Daniel-DHu** [MCZhi/Predictive-Decision#4]
Hello, Zhiyu,
Thank you for your work,
I would like to ask if during the training session, the code will report an error 'Environment multi scenario does not exist.' 
May I ask how to solve it.
Thank you!

**Comment by MCZhi** [comment]
Hi, @Donghu1876. I appreciate your interest in our work. Did you install smarts using `pip install "smarts[camera-obs] @ git+https://github.com/huawei-noah/SMARTS.git@comp-1"`? Because the environments we use are provided by the Driving Smarts competition, you need to install this specific version to access the environments.

**Comment by Daniel-DHu** [comment]
Thank you very much for your reply, which has answered my doubts.
I also encountered another error: "the module sumo has no attribute SUMO_HOME".
I hope to get your help. I would be very grateful!

**Comment by MCZhi** [comment]
Probably because you haven't installed SUMO properly. You can go to this https://github.com/huawei-noah/SMARTS/tree/comp-1#troubleshooting for help.

**Comment by Daniel-DHu** [comment]
Thank you again and wish you a bright future!

**Comment by MCZhi** [comment]
Thanks. Good luck with your research! Let me know if you need any help.
